spring:
    application:
        name: fslabs-workportal
    datasource:
        username: jobportal
        password: jobportal
        url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/jobportal
        driver-class-name: com.mysql.cj.jdbc.Driver
    servlet:
        multipart:
            max-file-size: 10MB
            max-request-size: 10MB
            enabled: true
application:
    security-portal:
        user: workportal@fleetstudio.com
        password: workportal@108

